# Generated by Django 2.2.9 on 2020-02-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='position',
            field=models.TextField(default='1st'),
        ),
    ]
