# Generated by Django 2.2.9 on 2020-02-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_timeline_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
