# Generated by Django 2.2.9 on 2020-02-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200205_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='timeline',
            name='content2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='content3',
            field=models.TextField(null=True),
        ),
    ]
