# Generated by Django 2.2.9 on 2020-02-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200213_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='media',
            field=models.ImageField(default='timeline_media/1st.png', upload_to='timeline_media'),
        ),
    ]
