# Generated by Django 2.2.9 on 2020-02-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200216_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='media',
            field=models.ImageField(upload_to='timeline_media'),
        ),
    ]
