# Generated by Django 2.2.9 on 2020-02-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200218_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='content1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='content3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
