# Generated by Django 2.2.9 on 2020-02-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200218_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='media',
            field=models.ImageField(default='2nd.gif', upload_to='timeline_media'),
        ),
    ]
