# Generated by Django 2.2.9 on 2020-03-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200218_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='media',
            field=models.ImageField(upload_to='timeline_media'),
        ),
    ]
