# Generated by Django 2.2.9 on 2020-03-29 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200323_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('media', models.ImageField(default='background copy.png', upload_to='blog_media')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
