# Generated by Django 2.2.9 on 2020-04-07 03:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200405_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
