# Generated by Django 3.0.7 on 2020-06-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_post2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post2',
        ),
    ]
