# Generated by Django 3.0.7 on 2020-09-19 17:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_post2'),
    ]

    operations = [
        migrations.CreateModel(
            name='post3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('media', models.ImageField(default='background copy.png', upload_to='blog_media')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
