# Generated by Django 2.2.9 on 2020-03-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200327_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(default='timeline_media/background copy.png', upload_to='blog_media'),
        ),
    ]
