# Generated by Django 2.2.9 on 2020-03-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(default='background copy.png', upload_to='blog_media'),
        ),
    ]
